# AUTOGENERATED! DO NOT EDIT! File to edit: dev/00_core.ipynb (unless otherwise specified).

__all__ = ['say_hi', 'hiSayer']

# Cell
def say_hi(to):
    "Say hi to someone"
    return f"Hi {to}"

# Cell
class hiSayer:
    "class that spams hi"
    def __init__(self,to):
        self.to=to
    def say(self):
        "calls function to say hi"
        return say_hi(self.to)